interface DeployOptions {
  name: string;
  gitRepository: {
    repo: string;
    type: "github";
  };
}

async function generateProtectionBypass(projectId: string) {
  const url = new URL(
    `https://api.vercel.com/v1/projects/${projectId}/protection-bypass`,
  );
  url.searchParams.append("teamId", process.env.VERCEL_TEAM_ID);

  const response = await fetch(url.toString(), {
    method: "PATCH",
    headers: {
      Authorization: `Bearer ${process.env.VERCEL_TOKEN}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      generate: {
        secret: `bypass-${Date.now()}`,
      },
    }),
  });

  const data = await response.json();
  return data.token;
}

export async function deployToVercel({ name, gitRepository }: DeployOptions) {
  if (!process.env.VERCEL_TOKEN) {
    throw new Error("VERCEL_TOKEN is required");
  }

  if (!process.env.VERCEL_TEAM_ID) {
    throw new Error("VERCEL_TEAM_ID is required");
  }

  try {
    // 1. Создаем проект
    console.log("Creating Vercel project...");
    const project = await createProject(name, gitRepository);
    console.log("Project created:", project);

    const bypassToken = await generateProtectionBypass(project.id);
    console.log("Generated bypass token:", bypassToken);

    // 2. Создаем деплоймент, используя то же имя
    console.log("Creating deployment...");
    const deployment = await createDeployment(
      project.id,
      gitRepository.repo,
      name,
    );
    console.log("Deployment created:", deployment);

    return {
      id: deployment.id,
      url: deployment.url,
      readyState: deployment.readyState,
      bypassToken,
    };
  } catch (error) {
    console.error("Vercel deployment failed:", error);
    throw error;
  }
}

async function createProject(
  name: string,
  gitRepository: DeployOptions["gitRepository"],
) {
  const projectData = {
    name,
    framework: "vite",
    gitRepository: {
      repo: gitRepository.repo,
      type: gitRepository.type,
    },
    buildCommand: "npm run build",
    installCommand: "npm install",
    outputDirectory: "dist",
  };

  const url = new URL("https://api.vercel.com/v10/projects");
  url.searchParams.append("teamId", process.env.VERCEL_TEAM_ID);

  console.log("Project request data:", projectData);

  const response = await fetch(url.toString(), {
    method: "POST",
    headers: {
      Authorization: `Bearer ${process.env.VERCEL_TOKEN}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(projectData),
  });

  const responseData = await response.json();
  console.log("Project response:", {
    status: response.status,
    statusText: response.statusText,
    data: responseData,
  });

  if (!response.ok) {
    throw new Error(
      `Failed to create project: ${JSON.stringify(responseData.error) || "Unknown error"}`,
    );
  }

  return responseData;
}

async function createDeployment(projectId: string, repo: string, name: string) {
  // Получаем информацию о проекте, чтобы взять правильный repoId
  const projectUrl = new URL(`https://api.vercel.com/v9/projects/${projectId}`);
  projectUrl.searchParams.append("teamId", process.env.VERCEL_TEAM_ID);

  const projectResponse = await fetch(projectUrl.toString(), {
    headers: {
      Authorization: `Bearer ${process.env.VERCEL_TOKEN}`,
    },
  });

  const project = await projectResponse.json();
  const repoId = project.link.repoId;

  const deployData = {
    name,
    gitSource: {
      type: "github",
      ref: "main",
      repoId: repoId,
    },
    target: "production",
    projectSettings: {
      framework: "vite",
      buildCommand: "npm run build",
      installCommand: "npm install",
      outputDirectory: "dist",
      nodeVersion: "18.x",
    },
  };

  console.log("Deployment request data:", deployData);

  const url = new URL(`https://api.vercel.com/v13/deployments`);
  url.searchParams.append("teamId", process.env.VERCEL_TEAM_ID);
  url.searchParams.append("projectId", projectId);

  const response = await fetch(url.toString(), {
    method: "POST",
    headers: {
      Authorization: `Bearer ${process.env.VERCEL_TOKEN}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(deployData),
  });

  const responseData = await response.json();
  console.log("Deployment response:", {
    status: response.status,
    statusText: response.statusText,
    data: responseData,
  });

  if (!response.ok) {
    throw new Error(
      `Failed to create deployment: ${responseData.error?.message || JSON.stringify(responseData)}`,
    );
  }

  return responseData;
}
